name: Upload Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instal dependencies
        run: |
          pip install pytest
          pip install requests
      - name: Test HTTP Enpoints from AWS Lambda functions
        run: |
          pwd
          ls
          cd PythonTests/
          python3 -m pytest -v
