name: Upload Backend

on:
  push:
    branches:
    - master
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Set up Python "3.9"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instal dependencies
        run: |
          pip install pytest
          pip install requests
      - name: Test HTTP Enpoints from AWS Lambda functions
        run: |
          cd ../../PythonTests/
          python3 -m pytest -v
      
